name: Bug Report
description: File a bug report.
type: "bug"
labels:
  - status/triage
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to report a bug!**
        If this is a security issue related to docker, please report it to the [Docker Security team](mailto:security@docker.com), see [SECURITY.md](https://github.com/moby/buildkit/blob/master/.github/SECURITY.md) for more information.

  - type: checkboxes
    attributes:
      label: Contributing guidelines and issue reporting guide
      description: |
        Please read the contributing guidelines and issue reporting guide before proceeding.
      options:
        - label: I've read the [contributing guidelines](https://github.com/dexnore/dexfile/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree. I've also read the [issue reporting guide](https://github.com/dexnore/dexfile/blob/master/.github/issue_reporting_guide.md).
          required: true

  - type: checkboxes
    attributes:
      label: Well-formed report checklist
      description: |
        Make sure that your request fulfills all of the following requirements.
        If one requirement cannot be satisfied, explain in detail why.
      options:
        - label: I have found a bug that the documentation does not mention anything about my problem
          required: true
        - label: I have found a bug that there are no open or closed issues that are related to my problem
          required: true
        - label: I have provided version/information about my environment and done my best to provide a reproducer
          required: true

  - type: textarea
    attributes:
      label: Description of bug
      description: |
        Please provide a description of the bug, reproduction steps and version information.

        <details>
        <summary>How to collect version information</summary>

        Using `buildctl` and `buildkitd` to get version information
        ```bash
        buildctl --version && buildkitd version
        ```

        Using `docker` to get BuildKit information
        ```bash
        docker buildx version && docker buildx inspect
        ```

        Add Docker Engine information (if available)
        ```bash
        docker version && docker info
        ```

        </details>
      value: |
        ## Bug description

        A description of the bug, observed, and expected behaviour.

        ## Reproduction

        Steps to reproduce the problem. If you are using `docker build` or `docker buildx build` providing the command as well as any input files will help analysis.

        ## Version information

        ```bash
        terminal_output
        ```
    validations:
      required: true