name: Feature or enhancement request
description: Missing functionality? Come tell us about it!
type: "enhancement"
labels:
  - status/triage

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the feature you want to see?
    validations:
      required: true